name: Release Please

on:
  push:
    branches: [main] # cuando merges develop -> main, se activa
  workflow_dispatch:

jobs:
  release-please:
    permissions:
      contents: write # crear tags/releases y commitear changelog
      pull-requests: write # abrir/actualizar el PR de release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-release: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
